name: latest

on:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true  # 👈 Important: Fetch LFS files too

      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs pull  # 👈 Important: Pull LFS-tracked files

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run chatbot app
        run: |
          pip install streamlit  # Optional if already in requirements.txt
          streamlit run ai-partner.py

